# Generated by Django 4.2.1 on 2023-05-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=100)),
                ('declension', models.IntegerField(default=0)),
                ('gradation', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WordForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordform', models.CharField(default='', max_length=100)),
                ('number', models.IntegerField(choices=[(1, 'Singular'), (2, 'Plural')])),
                ('case', models.CharField(choices=[('nominative', 'Nominative'), ('accusative', 'Accusative'), ('genitive', 'Genitive'), ('partitive', 'Partitive'), ('inessive', 'Inessive'), ('elative', 'Elative'), ('illative', 'Illative'), ('adessive', 'Adessive'), ('ablative', 'Ablative'), ('allative', 'Allative'), ('essive', 'Essive'), ('translative', 'Translative'), ('abessive', 'Abessive'), ('instructive', 'Instructive'), ('comitative', 'Comitative')], max_length=20)),
                ('baseform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.baseform')),
            ],
        ),
    ]
