# Generated by Django 4.2.1 on 2023-05-16 18:23

import os
from django.db import migrations
import json


def import_kotus_all_json(apps, schema_editor):
    # We can't import the BaseForm model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    BaseForm = apps.get_model("editor", "BaseForm")
    WordForm = apps.get_model("editor", "WordForm")

    filename = "kotus_all.json"

    with open(filename) as f:
        kotus_all = json.load(f)

    for word in kotus_all:
        baseform = BaseForm.objects.create(
            word=word["word"],
            declension=word["tn"],
            gradation=word["av"],
        )
        baseform
        word = WordForm.objects.create(
            baseform=baseform,
            wordform=word["word"],
            number=1,
            case="nominative",
        )
        word.save()


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0002_baseform_timestamp_wordform_timestamp"),
    ]

    operations = [
        migrations.RunPython(import_kotus_all_json),
    ]
