# Generated by Django 4.2.1 on 2023-05-16 18:23

import os
from django.db import migrations
import json


def import_kotus_all_json(apps, schema_editor):
    # We can't import the BaseForm model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    BaseForm = apps.get_model("editor", "BaseForm")
    WordForm = apps.get_model("editor", "WordForm")

    filename = "kotus_all.json"

    with open(filename) as f:
        kotus_all = json.load(f)

    for word in kotus_all:
        declension = word["tn"]
        if declension > 52:
            continue
        baseform, created = BaseForm.objects.update_or_create(
            word=word["word"],
            declension=declension,
            gradation=word["av"],
        )
        if created:
            baseform.save()
        word, created = WordForm.objects.update_or_create(
            baseform=baseform,
            wordform=word["word"],
            number=1,
            case="nominative",
        )
        if created:
            word.save()


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0002_baseform_timestamp_wordform_timestamp"),
    ]

    operations = [
        migrations.RunPython(import_kotus_all_json),
    ]
