# Generated by Django 4.2.1 on 2023-05-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20230516_1823'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baseform',
            unique_together={('word', 'declension', 'gradation')},
        ),
    ]
