# Generated by Django 4.2.1 on 2023-05-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_alter_baseform_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordform',
            unique_together={('baseform', 'wordform', 'number', 'case')},
        ),
    ]
