# Generated by Django 4.2.1 on 2023-05-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0005_alter_wordform_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordform",
            name="case",
            field=models.CharField(
                choices=[
                    ("nominative", "Nominative"),
                    ("genitive", "Genitive"),
                    ("partitive", "Partitive"),
                    ("inessive", "Inessive"),
                    ("elative", "Elative"),
                    ("illative", "Illative"),
                    ("adessive", "Adessive"),
                    ("ablative", "Ablative"),
                    ("allative", "Allative"),
                    ("essive", "Essive"),
                    ("translative", "Translative"),
                    ("abessive", "Abessive"),
                    ("instructive", "Instructive"),
                    ("comitative", "Comitative"),
                    ("accusative", "Accusative"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ExampleCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("declension", models.IntegerField(default=0)),
                ("gradation", models.CharField(default="", max_length=1)),
                ("size", models.IntegerField(default=0)),
                ("examples", models.TextField(default="")),
            ],
            options={
                "unique_together": {("declension", "gradation")},
            },
        ),
    ]
