# Generated by Django 4.2.1 on 2023-05-19 17:49

from django.db import migrations


# Populate the example cache with the examples
def populate_example_cache(apps, schema_editor):
    ExampleCache = apps.get_model("editor", "ExampleCache")
    BaseForm = apps.get_model("editor", "BaseForm")

    combinations = (
        BaseForm.objects.order_by("declension", "gradation")
        .values_list("declension", "gradation")
        .distinct()
    )

    for declension, gradation in combinations:
        # get the count of BaseForms with this declension and gradation
        size = BaseForm.objects.filter(
            declension=declension, gradation=gradation
        ).count()
        # get the examples (5 random examples)
        examples = BaseForm.objects.filter(
            declension=declension, gradation=gradation
        ).order_by("?")[:5]

        item, created = ExampleCache.objects.update_or_create(
            declension=declension,
            gradation=gradation,
            size=size,
            examples=", ".join([example.word for example in examples]),
        )

        if created:
            item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0006_alter_wordform_case_examplecache"),
    ]

    operations = [migrations.RunPython(populate_example_cache)]
