# Generated by Django 4.2.1 on 2023-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_auto_20230519_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordform',
            name='source',
            field=models.CharField(choices=[('kotus', 'Kotus'), ('editor', 'Editor')], default='kotus', max_length=20),
        ),
    ]
