# Generated by Django 4.2.1 on 2023-05-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_wordform_source'),
    ]

    operations = [
    ]
